# Docker
# Build and push an image to Azure Container Registry
# https://docs.microsoft.com/azure/devops/pipelines/languages/docker
#

trigger:
- none

resources:
- repo: self

variables:
  # Container registry service connection established during pipeline creation
  dockerRegistryServiceConnection: '1264ab9f-f5fc-4654-80ba-08a69d4a039f'
  imageRepository: 'thursdaydemo'
  containerRegistry: 'dockerdemoacr2.azurecr.io'
  dockerfilePath: '$(Build.SourcesDirectory)/mywebapi/Dockerfile'
  tag: '$(Build.BuildId)'
  
  # Agent VM image name
  vmImageName: 'ubuntu-latest'

stages:
- stage: Build_Web_Api
  displayName: Build,push, deploy to k8s
  jobs:  
  - job: Build
    displayName: Build
    pool:
      vmImage: $(vmImageName)
    steps:
    - task: Docker@2
      displayName: Build and push web api image to container registry
      inputs:
        containerRegistry: '$(dockerRegistryServiceConnection)'
        repository: '$(imageRepository)-webapi'
        command: 'buildAndPush'
        Dockerfile: '**/mywebapi/Dockerfile'
        tags: '$(tag)'

    - task: Bash@3
      displayName: Update the WebApp Yaml for k8s
      inputs:
        targetType: 'inline'
        script: 'bash -c "sed -i ''s/BuildNumber/$(Build.BuildId)/g'' backend-webapi.yaml"'


    - task: Kubernetes@1
      displayName: Publish App Yaml to k8s
      inputs:
        connectionType: 'Azure Resource Manager'
        azureSubscriptionEndpoint: 'Microsoft Azure Internal Consumption (18c9a476-0820-4be7-afc7-6d1fea9fd71e)'
        azureResourceGroup: 'rg-aks-win-only'
        kubernetesCluster: 'myAKSWinCluster'
        namespace: 'default'
        command: 'apply'
        useConfigurationFile: true
        configuration: 'backend-webapi.yaml'
        secretType: 'dockerRegistry'
        containerRegistryType: 'Azure Container Registry'
        azureSubscriptionEndpointForSecrets: 'Microsoft Azure Internal Consumption (18c9a476-0820-4be7-afc7-6d1fea9fd71e)'
        azureContainerRegistry: 'dockerdemoacr2.azurecr.io'
        secretName: 'acr'

- stage: Build_Web_App
  displayName: Build, push, deploy Web App
  jobs:  
  - job: Build
    displayName: Build
    pool:
      vmImage: $(vmImageName)
    steps:
#    - task: Bash@3
#      displayName: Update the WebApp Yaml for k8s
#      inputs:
#        targetType: 'inline'
#        script: 'bash -c "sed -i ''s/BuildNumber/$(Build.BuildId)/g'' frontend-webapp.yaml"'




#    - task: Docker@2
#      displayName: Build and push an web app to container registry
#      inputs:
#        containerRegistry: '$(dockerRegistryServiceConnection)'
#        repository: '$(imageRepository)-webapp'
#        command: 'buildAndPush'
#        Dockerfile: '**/mywebapp/Dockerfile'
#        tags: '$(tag)'


#    - task: Kubernetes@1
#      displayName: Publish App Yaml to k8s
#      inputs:
#        connectionType: 'Azure Resource Manager'
#        azureSubscriptionEndpoint: 'Microsoft Azure Internal Consumption (18c9a476-0820-4be7-afc7-6d1fea9fd71e)'
#        azureResourceGroup: 'rg-aks-win-only'
#        kubernetesCluster: 'myAKSWinCluster'
#        namespace: 'default'
#        command: 'apply'
#        useConfigurationFile: true
#        configuration: 'frontend-webapp.yaml'
#        secretType: 'dockerRegistry'
#        containerRegistryType: 'Azure Container Registry'
#        azureSubscriptionEndpointForSecrets: 'Microsoft Azure Internal Consumption (18c9a476-0820-4be7-afc7-6d1fea9fd71e)'
#        azureContainerRegistry: 'dockerdemoacr2.azurecr.io'
#        secretName: 'acr'

    - task: Kubernetes@1
      inputs:
        connectionType: 'Kubernetes Service Connection'
        kubernetesServiceEndpoint: 'devops-sa'
        namespace: 'default'
        command: 'apply'
        useConfigurationFile: true
        configuration: 'frontend-webapp.yaml'
#        secretType: 'dockerRegistry'
#        containerRegistryType: 'Azure Container Registry'
#        azureSubscriptionEndpointForSecrets: 'Microsoft Azure Internal Consumption (18c9a476-0820-4be7-afc7-6d1fea9fd71e)'
#        azureContainerRegistry: 'dockerdemoacr2.azurecr.io'
#        secretName: 'acr'